import { Inter } from "next/font/google";
import "./globals.css";
import Authprovider from "@/app/Authprovider/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecomm Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
        {children}
        </Authprovider>
        </body>
    </html>
  );
}
